/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/Parrot.glb");

  // Refs for the wings
  const leftWingRef = useRef();
  const rightWingRef = useRef();
  const grpRef = useRef();
  const birdRef = useRef();

  useFrame(({ clock }) => {
    const time = clock.getElapsedTime();
    const flap = Math.sin(time * 2) * 0.1; // Adjust speed and amplitude
    // if (leftWingRef.current) {
    //   leftWingRef.current.rotation.z = flap; // Adjust axis if needed
    // }
    // if (rightWingRef.current) {
    //   rightWingRef.current.rotation.z = -flap; // Opposite direction for symmetry
    // }
    if (grpRef.current) {
      grpRef.current.rotation.z = flap;
    }
    if (birdRef.current) {
      birdRef.current.position.x += flap;
    }
  });

  return (
    <group {...props} dispose={null} ref={birdRef}>
      {/* Eyes */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Parrot3-Mesh"].geometry}
        material={materials["Mat.3"]}
      />
      {/* Main Body */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Parrot3-Mesh_1"].geometry}
        material={materials.Mat}
      />
      <group ref={grpRef}>
        {/* Tail and wings (dark blue) */}
        <mesh
          ref={leftWingRef}
          castShadow
          receiveShadow
          geometry={nodes["Parrot3-Mesh_2"].geometry}
          material={materials["Mat.2"]}
        />
        {/* Light blue wings */}
        <mesh
          ref={rightWingRef}
          castShadow
          receiveShadow
          geometry={nodes["Parrot3-Mesh_3"].geometry}
          material={materials["Mat.1"]}
        />
      </group>
      {/* Beak and gray color below eyes */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Parrot3-Mesh_4"].geometry}
        material={materials["Mat.4"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Parrot.glb");
